# Generated by Django 3.1.5 on 2021-01-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('sales', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'sales_2020Q4',
                'managed': False,
            },
        ),
    ]
